USE [TestDB]
GO

IF OBJECT_ID(N'dbo.PRODUCT', N'U') IS NOT NULL
   DROP TABLE [dbo].[PRODUCT];
GO

CREATE TABLE [dbo].[PRODUCT](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(100) NOT NULL,
	[Price] [MONEY] NOT NULL,
	[ReleaseDate] [DATETIME] NULL,
	[isProductDeleted] BIT NULL
	
 CONSTRAINT [PK_PO_ID] PRIMARY KEY CLUSTERED
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCT] ADD  CONSTRAINT [DF_PRODUCT_IS_DELETED]  DEFAULT ((0)) FOR [isProductDeleted]
GO


